export const quickAdminSidebarMenu = [
  {
    type: "link",
    label: "Dashboard",
    path: "/admin/quick-commerce",
    icon: "LayoutDashboard",
  },
  {
    type: "section",
    label: "CORE MANAGEMENT",
    items: [
      {
        type: "link",
        label: "Seller Requests",
        path: "/admin/quick-commerce/seller-requests",
        icon: "ClipboardCheck",
      },
      {
        type: "expandable",
        label: "Categories",
        icon: "FolderTree",
        subItems: [
          { label: "All Categories", path: "/admin/quick-commerce/categories/hierarchy" },
          { label: "Header Categories", path: "/admin/quick-commerce/categories/header" },
          { label: "Main Categories", path: "/admin/quick-commerce/categories/level2" },
          { label: "Sub-Categories", path: "/admin/quick-commerce/categories/sub" },
        ],
      },
      { type: "link", label: "Products", path: "/admin/quick-commerce/products", icon: "Package" },
      { type: "link", label: "Zone Setup", path: "/admin/quick-commerce/zone-setup", icon: "MapPin" },
      {
        type: "expandable",
        label: "Marketing Tools",
        icon: "Megaphone",
        subItems: [
          { label: "Content Manager", path: "/admin/quick-commerce/experience-studio" },
          { label: "Hero & Categories Per Page", path: "/admin/quick-commerce/hero-categories" },
          { label: "Send Notifications", path: "/admin/quick-commerce/notifications" },
          { label: "Coupons & Promos", path: "/admin/quick-commerce/coupons" },
          { label: "Offer Sections", path: "/admin/quick-commerce/offer-sections" },
          { label: "Shop by Store", path: "/admin/quick-commerce/shop-by-store" },
        ],
      },
      {
        type: "expandable",
        label: "Customer Support",
        icon: "MessageSquare",
        subItems: [
          { label: "Help Tickets", path: "/admin/quick-commerce/support-tickets" },
          { label: "Review Content", path: "/admin/quick-commerce/moderation" },
        ],
      },
      {
        type: "expandable",
        label: "Sellers",
        icon: "Building2",
        subItems: [
          { label: "Active Sellers", path: "/admin/quick-commerce/sellers/active" },
          { label: "Waiting for Review", path: "/admin/quick-commerce/sellers/pending" },
          { label: "Seller Locations", path: "/admin/quick-commerce/seller-locations" },
          { label: "Seller Commission", path: "/admin/quick-commerce/sellers/commission" },
        ],
      },
      {
        type: "expandable",
        label: "Delivery Drivers",
        icon: "Truck",
        subItems: [
          { label: "Active Drivers", path: "/admin/quick-commerce/delivery-boys/active" },
          { label: "Waiting for Review", path: "/admin/quick-commerce/delivery-boys/pending" },
          { label: "Track Drivers", path: "/admin/quick-commerce/tracking" },
          { label: "Send Money", path: "/admin/quick-commerce/delivery-funds" },
        ],
      },
      { type: "link", label: "Wallet", path: "/admin/quick-commerce/wallet", icon: "Wallet" },
      { type: "link", label: "Money Requests", path: "/admin/quick-commerce/withdrawals", icon: "CreditCard" },
      { type: "link", label: "Seller Payments", path: "/admin/quick-commerce/seller-transactions", icon: "Receipt" },
      { type: "link", label: "Collect Cash", path: "/admin/quick-commerce/cash-collection", icon: "IndianRupee" },
      { type: "link", label: "Customers", path: "/admin/quick-commerce/customers", icon: "Users" },
      { type: "link", label: "FAQs", path: "/admin/quick-commerce/faqs", icon: "MessageSquare" },
      {
        type: "expandable",
        label: "Orders",
        icon: "FileText",
        subItems: [
          { label: "All Orders", path: "/admin/quick-commerce/orders/all" },
          { label: "New Orders", path: "/admin/quick-commerce/orders/pending" },
          { label: "Being Prepared", path: "/admin/quick-commerce/orders/processed" },
          { label: "On the Way", path: "/admin/quick-commerce/orders/out-for-delivery" },
          { label: "Delivered", path: "/admin/quick-commerce/orders/delivered" },
          { label: "Cancelled", path: "/admin/quick-commerce/orders/cancelled" },
          { label: "Returned", path: "/admin/quick-commerce/orders/returned" },
        ],
      },
      { type: "link", label: "Fees & Charges", path: "/admin/quick-commerce/billing", icon: "DollarSign" },
      { type: "link", label: "My Profile", path: "/admin/quick-commerce/profile", icon: "User" },
    ],
  },
]
