export const returnStatuses = {
  RETURN_REQUESTED: 'RETURN_REQUESTED',
  RETURN_APPROVED: 'RETURN_APPROVED',
  RETURN_REJECTED: 'RETURN_REJECTED',
  RETURN_PICKUP_ASSIGNED: 'RETURN_PICKUP_ASSIGNED',
  PICKED_UP: 'PICKED_UP',
  RETURN_RECEIVED_BY_SELLER: 'RETURN_RECEIVED_BY_SELLER',
  REFUND_COMPLETED: 'REFUND_COMPLETED'
};
